"""Tests for the lock drift check.

It runs on every ./lint.sh, so a bug here is a guarantee silently not
being enforced -- which is the same failure the check itself exists to
catch, one level up.
"""

import pytest

from scripts.check_lockfiles import _declared, _locked, _normalize, main


def test_the_real_lock_files_agree(capsys):
    # The check against this repository's actual files. If someone adds
    # a dependency without regenerating, this fails in the test suite as
    # well as in lint.sh.
    assert main() == 0
    assert "agree" in capsys.readouterr().out


def test_declared_names_ignore_comments_bounds_and_extras(tmp_path):
    path = tmp_path / "requirements.txt"
    path.write_text(
        "# a comment\n"
        "\n"
        "psycopg[binary]>=3.2,<4\n"
        "PyYAML>=6.0,<7\n"
        "import-linter>=2.0,<3\n"
    )
    assert _declared(path) == {"psycopg", "pyyaml", "import-linter"}


def test_locked_names_ignore_hash_continuation_lines(tmp_path):
    # Lock entries are a name line followed by indented --hash lines.
    # Treating a hash line as a package name would make every lock look
    # like it contained dozens of phantom packages, and the check would
    # never fail.
    path = tmp_path / "requirements.lock"
    path.write_text(
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv pip compile requirements.txt\n"
        "psycopg==3.3.5 \\\n"
        "    --hash=sha256:abc \\\n"
        "    --hash=sha256:def\n"
        "pyyaml==6.0.2 \\\n"
        "    --hash=sha256:ghi\n"
    )
    assert _locked(path) == {"psycopg", "pyyaml"}


@pytest.mark.parametrize(("raw", "expected"), [
    ("import-linter", "import-linter"),
    ("import_linter", "import-linter"),
    ("Import.Linter", "import-linter"),
    ("PyYAML", "pyyaml"),
])
def test_normalization_matches_pypi_rules(raw, expected):
    # Without this, `import-linter` in a requirements file and
    # `import_linter` in a lock read as two different packages and the
    # check reports drift that is not there.
    assert _normalize(raw) == expected
